# Project Configuration
[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = false

# Authorized origins
allow_origins = ["*"]

# Features Configuration
[features]
# Show the prompt playground
prompt_playground = true

# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = false

# Automatically tag threads with the current chat profile (if a chat profile is used)
auto_tag_thread = true

# Spontaneous File Upload Configuration
[features.spontaneous_file_upload]
enabled = true
accept = ["*/*"]
max_files = 20
max_size_mb = 500

# Audio Configuration
[features.audio]
min_decibels = -45
initial_silence_timeout = 3000
silence_timeout = 1500
max_duration = 15000
chunk_duration = 1000
sample_rate = 44100

# UI Configuration
[UI]
# Name of the app and chatbot.
name = "Chatbot"

# Show the readme while the thread is empty.
show_readme_as_default = false

# Large size content are by default collapsed for a cleaner ui
default_collapse_content = true

# The default value for the expand messages settings.
default_expand_messages = false

# Hide the chain of thought details from the user in the UI.
hide_cot = false

# Dark Theme Configuration
[UI.theme.dark]
# Background color
background = "#121212"

# Paper color
paper = "#1E1E1E"

# Primary color configuration
[UI.theme.dark.primary]
# Main color
main = "#FF4081"

# Dark variant of the primary color
dark = "#F50057"

# Light variant of the primary color
light = "#FF80AB"

# Metadata
[meta]
# Tool version that generated this configuration
generated_by = "1.1.101"
